### ISSUE TITLE
I get error when call scanQr method

### ISSUE THREAD

**Issue by godlessturtle** [maja0270558/majascan_flutter#15]
It works on ios very well, but on android closes app when i call the _scanQr method, i also added the line below to android manifest

`<activity android:name="com.djgeo.majascan.g_scanner.QrCodeScannerActivity"/>`

```
Future _scanQR() async {
      String qrResult = await MajaScan.startScan(title: "Karekod Tara", titleColor: Colors.blue, flashlightEnable: false, qRScannerColor: Colors.blue, qRCornerColor: Colors.blue);
}
```

```
W/ActivityThread(23399): handleWindowVisibility: no activity for token android.os.BinderProxy@c71ab35
D/ZrHung.AppEyeUiProbe(23399): notify runnable to start.
V/ActivityThread(23399): Skipping new config:{1.0 286mcc3mnc [tr_TR] ldltr sw423dp w423dp h838dp 408dpi nrml long port finger -keyb/v/h -nav/h winConfig={ mBounds=Rect(0, 0 - 2138, 1080) mAppBounds=Rect(0, 85 - 1080, 2222) mWindowingMode=fullscreen mActivityType=undefined} nonFullScreen=0 suim:4 s.353}, config:{1.0 286mcc3mnc [tr_TR] ldltr sw423dp w423dp h838dp 408dpi nrml long port finger -keyb/v/h -nav/h winConfig={ mBounds=Rect(0, 0 - 2138, 1080) mAppBounds=Rect(0, 85 - 1080, 2222) mWindowingMode=fullscreen mActivityType=undefined} nonFullScreen=0 suim:4 s.353} for app:com.ikradap.alfatest
V/ActivityThread(23399): callActivityOnCreate
I/HwPhoneWindow(23399): updateLayoutParamsColor false mSpecialSet=false, mForcedNavigationBarColor=false, navigationBarColor=0, mNavBarShow=false, mIsFloating=false
I/HwPhoneWindow(23399): updateLayoutParamsColor true mSpecialSet=true, mForcedNavigationBarColor=false, navigationBarColor=fffcfcfc, mNavBarShow=false, mIsFloating=false
W/kradap.alfates(23399): Accessing hidden method Landroid/view/View;->computeFitSystemWindows(Landroid/graphics/Rect;Landroid/graphics/Rect;)Z (light greylist, reflection)
W/kradap.alfates(23399): Accessing hidden method Landroid/view/ViewGroup;->makeOptionalFitsSystemWindows()V (light greylist, reflection)
D/QrCodeScannerActivity(23399): QrCodeScannerActivity:1
D/ActivityThread(23399): add activity client record, r= ActivityRecord{75a166e token=android.os.BinderProxy@c71ab35 {com.ikradap.alfatest/com.djgeo.majascan.g_scanner.QrCodeScannerActivity}} token= android.os.BinderProxy@c71ab35
I/kradap.alfates(23399): Starting profile saver IsSaveProfileNow end.
D/TextView(23399): get Display Panel Type is : 0
D/AndroidRuntime(23399): Shutting down VM
E/AndroidRuntime(23399): FATAL EXCEPTION: main
E/AndroidRuntime(23399): Process: com.ikradap.alfatest, PID: 23399
E/AndroidRuntime(23399): java.lang.NoClassDefFoundError: Failed resolution of: Lkotlin/KotlinPackage;
E/AndroidRuntime(23399): 	at com.djgeo.majascan.g_scanner.ScanFragment.handleBundleData(ScanFragment.kt:140)
E/AndroidRuntime(23399): 	at com.djgeo.majascan.g_scanner.ScanFragment.onViewCreated(ScanFragment.kt:108)
E/AndroidRuntime(23399): 	at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManager.java:1471)
E/AndroidRuntime(23399): 	at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1784)
E/AndroidRuntime(23399): 	at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManager.java:1852)
E/AndroidRuntime(23399): 	at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:802)
E/AndroidRuntime(23399): 	at androidx.fragment.app.FragmentManagerImpl.executeOps(FragmentManager.java:2625)
E/AndroidRuntime(23399): 	at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2411)
E/AndroidRuntime(23399): 	at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2366)
E/AndroidRuntime(23399): 	at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2273)
E/AndroidRuntime(23399): 	at androidx.fragment.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3273)
E/AndroidRuntime(23399): 	at androidx.fragment.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:3229)
E/AndroidRuntime(23399): 	at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:201)
E/AndroidRuntime(23399): 	at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:620)
E/AndroidRuntime(23399): 	at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:178)
E/AndroidRuntime(23399): 	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1419)
E/AndroidRuntime(23399): 	at android.app.Activity.performStart(Activity.java:7479)
E/AndroidRuntime(23399): 	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3454)
E/AndroidRuntime(23399): 	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:180)
E/AndroidRuntime(23399): 	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:165)
E/AndroidRuntime(23399): 	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:142)
E/AndroidRuntime(23399): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
E/AndroidRuntime(23399): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2199)
E/AndroidRuntime(23399): 	at android.os.Handler.dispatchMessage(Handler.java:112)
E/AndroidRuntime(23399): 	at android.os.Looper.loop(Looper.java:216)
E/AndroidRuntime(23399): 	at android.app.ActivityThread.main(ActivityThread.java:7625)
E/AndroidRuntime(23399): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(23399): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
E/AndroidRuntime(23399): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
E/AndroidRuntime(23399): Caused by: java.lang.ClassNotFoundException: Didn't find class "kotlin.KotlinPackage" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/com.ikradap.alfatest-mQCYcN-jAa8S9ff85MHEsg==/base.apk"],nativeLibraryDirectories=[/data/app/com.ikradap.alfatest-mQCYcN-jAa8S9ff85MHEsg==/lib/arm64, /data/app/com.ikradap.alfatest-mQCYcN-jAa8S9ff85MHEsg==/base.apk!/lib/arm64-v8a, /system/lib64, /product/lib64]]
E/AndroidRuntime(23399): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
E/AndroidRuntime(23399): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
E/AndroidRuntime(23399): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
E/AndroidRuntime(23399): 	... 29 more
I/Process (23399): Sending signal. PID: 23399 SIG: 9

```

**Comment by XYZ0204** [comment]
please check android folder:

 **build.gradle**

```
buildscript {
    ext.kotlin_version = '1.2.71'
    repositories {
        google()
        jcenter()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:3.2.1'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}
```
###  kotlin_version

and please add android/app folder:

 **build.gradle**

```
apply plugin: 'kotlin-android
```
Thank you

**Comment by godlessturtle** [comment]
sorry for bothering, i missed add the line below to my app/build.gradle file, it works now. thank you for your response

`apply plugin: 'kotlin-android`
